package com.github.litermc.vsprinter.api;

public enum PrintStatus {
	UNCONSTRUCTED,
	IDLE,
	WORKING,
	EMPTY_BLUEPRINT,
	INVALID,
	SCALE_TOO_SMALL,
	SCALE_TOO_LARGE,
	NOT_ENOUGH_SPACE,
	REQUIRE_ENERGY,
	REQUIRE_MATERIAL;
}
